### ISSUE TITLE
Option to port Chord-Provider to Linux

### ISSUE THREAD

**Issue by CodeShakingSheep** [Desbeers/Chord-Provider#17]
Wow, this app looks awesome based on the screenshot in the README file 😍 . Exactly what I've been looking for. The only thing is I'm not on a Mac. My laptop runs Linux (Ubuntu). Could this app somehow be ported / made available for Linux based OS? I'd be willing to contribute to it. 

If not, does anyone know of any equivalent Linux alternative to Chord-Provider? I did quite a bit of research on this but couldn't find anything good. I'm running the ChordPro desktop app on my laptop. However, I want to be able to select different songs faster and see a live preview of it without having to generate it every time. Grateful for any hints 🙏

**Comment by Desbeers** [comment]
While `Swift` is open source and available on Linux, `SwiftUI` is neither and that is what I’m using now for the UI. So its not easy to rewrite the user interface for Linux but it is on my list.

- Move the non-UI stuff to Foundation (in progress)
- Trying [SwiftCrossUI](https://github.com/stackotter/swift-cross-ui) as UI.

But don’t expect any result soon...

**Comment by Desbeers** [comment]
The ChordProviderCLI package does run on Linux.... Work in Progress!

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/e74f59ff-2ffe-4155-bd47-dc0ffc1cd606" />

**Comment by CodeShakingSheep** [comment]
Wow, that's awesome @Desbeers 🤩 Can I help with testing in any way? While I'm comfortable using a CLI I actually prefer a GUI.

**Comment by Desbeers** [comment]
So do I, but the UI is the hard part....

**Comment by CodeShakingSheep** [comment]
> So do I, but the UI is the hard part....

As I wrote I'd be willing to test / contribute if that helps.

**Comment by Desbeers** [comment]
<img width="562" height="412" alt="Image" src="https://github.com/user-attachments/assets/f7bfb0fd-8f6d-4a1c-b5ee-7e1899536a17" />

Added a Gnome version. With [adwaita-swift](https://git.aparoksha.dev/aparoksha/adwaita-swift). 

Super buggy! Feel free to test :-)

**Comment by Desbeers** [comment]
Progress...

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/0bf6d8e5-eb04-4c12-8b23-2aedad6e5e5c" />

**Comment by CodeShakingSheep** [comment]
That's amazing! 😍 
Just tried to test it but having a bunch of compiler issues.
```
/home/uh/Repositories/Github/Chord-Provider/ChordProviderGnome/.build/checkouts/adwaita-swift/Sources/Core/View/NavigationView+.swift:109:17: error: cannot find 'adw_navigation_view_pop' in scope
107 |         case .pop:
108 |             if storages.count > 1 {
109 |                 adw_navigation_view_pop(storage.opaquePointer)
    |                 `- error: cannot find 'adw_navigation_view_pop' in scope
110 |                 storages.removeLast()
111 |             } else { print("Warning: removing the initial view is not allowed.") }

/home/uh/Repositories/Github/Chord-Provider/ChordProviderGnome/.build/checkouts/adwaita-swift/Sources/Core/View/NavigationView+.swift:116:13: error: cannot find 'adw_navigation_view_push' in scope
114 |             contentStorage.fields[Self.componentID] = component
115 |             storages.append(contentStorage)
116 |             adw_navigation_view_push(
    |             `- error: cannot find 'adw_navigation_view_push' in scope
117 |                 storage.opaquePointer,
118 |                 adw_navigation_page_new(contentStorage.opaquePointer?.cast(), component.description)

/home/uh/Repositories/Github/Chord-Provider/ChordProviderGnome/.build/checkouts/adwaita-swift/Sources/Core/View/NavigationView+.swift:118:17: error: cannot find 'adw_navigation_page_new' in scope
116 |             adw_navigation_view_push(
117 |                 storage.opaquePointer,
118 |                 adw_navigation_page_new(contentStorage.opaquePointer?.cast(), component.description)
    |                 `- error: cannot find 'adw_navigation_page_new' in scope
119 |             )
120 |         default:

/home/uh/Repositories/Github/Chord-Provider/ChordProviderGnome/.build/checkouts/adwaita-swift/Sources/Core/View/NavigationView+.swift:118:71: error: generic parameter 'T' could not be inferred
116 |             adw_navigation_view_push(
117 |                 storage.opaquePointer,
118 |                 adw_navigation_page_new(contentStorage.opaquePointer?.cast(), component.description)
    |                                                                       `- error: generic parameter 'T' could not be inferred
119 |             )
120 |         default:

/home/uh/Repositories/Github/Chord-Provider/ChordProviderGnome/.build/checkouts/adwaita-swift/Sources/Core/Model/Extensions/OpaquePointer.swift:12:17: note: in call to function 'cast()'
10 |     /// Convert an opaque pointer into an unsafe mutable pointer with a defined type.
11 |     /// - Returns: The unsafe mutable pointer.
12 |     public func cast<T>() -> UnsafeMutablePointer<T> {
   |                 `- note: in call to function 'cast()'
13 |         .init(self)
14 |     }

/home/uh/Repositories/Github/Chord-Provider/ChordProviderGnome/.build/checkouts/adwaita-swift/Sources/Core/View/OverlaySplitView+.swift:34:13: error: cannot find 'adw_overlay_split_view_set_sidebar_position' in scope
32 |         var newSelf = self
33 |         newSelf.updateFunctions.append { storage, _, _ in
34 |             adw_overlay_split_view_set_sidebar_position(storage.opaquePointer, trailing ? GTK_PACK_END : GTK_PACK_START)
   |             `- error: cannot find 'adw_overlay_split_view_set_sidebar_position' in scope
35 |         }
36 |         return newSelf
```

Tried both to build with Swift 5 and Swift 6 on Ubuntu 22.04. Same errors. Any idea about this?

**Comment by Desbeers** [comment]
Ubuntu 22.04 is pretty old; I guess your libadwaita is outdated...

**Comment by Desbeers** [comment]
Ok, forget about `adwaita-swift`. While I like the effort (and the language is known for me), it gave me more troubles than fun in the end.

I found an *Open Source* project that would help me a lot to reach my goal:

[MibiMdEditor](https://github.com/mibi88/MibiMdEditor)

Hacked it to use my `chordprovider` CLI and displays the HTML.

The UI is written in [Vala](https://vala.dev) and that is close enough for me to use. And well supported.

It is using *whatever* script to produce output to `stdout`. So I can use my `Swift` CLI version of **Chord Provider** :-)

<img width="1122" height="909" alt="Image" src="https://github.com/user-attachments/assets/e7332b7d-55e5-4c39-ac52-5aa4ac9c3c21" />

Best of both worlds!

Don’t expect results soon. While I’m a good programmer for `Swift` and `SwiftUI` on the Mac, this is new to me.

**Comment by Desbeers** [comment]
Ok, that was not a good idea of mine.... Terrible editor performance with live updating.... Back to `Adwaita-swift`...

At least I've learned a lot about GTK already!

**Comment by CodeShakingSheep** [comment]
Ok, I will look for a backport of libadwaita for Ubuntu 22.04. Which libadwaita version are you using on your system?

**Comment by Desbeers** [comment]
I’m on Fedora 42, libAdwaita 1.6.9.

Building Flatpaks on my system gives crashes when running; building `swift run` works great.

I cannot be bothered for now; writing this for my own fun :-)

Why backport?

**Comment by Desbeers** [comment]
<img width="1209" height="910" alt="Image" src="https://github.com/user-attachments/assets/71e47000-459f-4b28-b554-525f871bf491" />

**Comment by CodeShakingSheep** [comment]
Forget about the backport. I got it to build and run using `flatpak-builder`. Ran into build errors first which I managed to fix. The flatpak app manifest had to be moved to the projects root directory in order for the local dependencies (`ChordProviderCore`, `ChordProviderHTML` and `GtkSourceView`) to build. This is how the flatpak manifest looks like

```json
{
  "app-id": "nl.desbeers.chordprovider",
  "runtime": "org.gnome.Platform",
  "runtime-version": "48",
  "sdk": "org.gnome.Sdk",
  "sdk-extensions": [
    "org.freedesktop.Sdk.Extension.swift6"
  ],
  "command": "ChordProvider",
  "finish-args": [
    "--share=ipc",
    "--socket=fallback-x11",
    "--device=dri",
    "--socket=wayland",
    "--filesystem=xdg-config/fontconfig:ro"
  ],
  "build-options": {
    "append-path": "/usr/lib/sdk/swift6/bin",
    "prepend-ld-library-path": "/usr/lib/sdk/swift6/lib"
  },
  "cleanup": [
    "/include",
    "/lib/pkgconfig",
    "/man",
    "/share/doc",
    "/share/gtk-doc",
    "/share/man",
    "/share/pkgconfig",
    "*.la",
    "*.a"
  ],
 "modules": [
    {
      "name": "ChordProvider",
      "buildsystem": "simple",
      "build-commands": [
        "cd ChordProviderGnome && swift build -c release --static-swift-stdlib",
        "install -Dm755 ChordProviderGnome/.build/release/ChordProvider /app/bin/ChordProvider",
        "cp -r ChordProviderGnome/.build/release/GtkSourceView_SourceView.resources /app/bin/"
      ],
      "sources": [
        { "type": "dir", "path": "." }
      ],
      "environment": {
        "GTK_A11Y": "none"
      }
    }
  ]
}
```

With that I could successfully build `flatpak-builder build nl.desbeers.chordprovider.json --force-clean` and then run with `flatpak-builder --run build nl.desbeers.chordprovider.json ChordProvider`.

<img width="1147" height="601" alt="Image" src="https://github.com/user-attachments/assets/fdbfaf44-9430-4a49-83cf-a6b5ebe3e9c3" />

**Comment by Desbeers** [comment]
Nice!

I use Gnome Builder for building; it did found the manifest in the `ChordProviderGnome` folder. But I moved it to the root now.

My previous crashes with flatpak was because of a bug in `adwaita-swift` that was fixed yesterday.

I can see on your screenshot that you are missing two icons on the top left; they are there for me...

**Comment by CodeShakingSheep** [comment]
Cool! 🤩 Just pulled the latest commits in. Ran into a few issues.

1. `chordpro.lang` not found
```
Running: install -Dm644 ChordProviderGnome/.build/debug/GtkSourceView_SourceView.resources/chordpro.lang /app/bin/GtkSourceView_SourceView.resources/chordpro.lang
install: cannot stat 'ChordProviderGnome/.build/debug/GtkSourceView_SourceView.resources/chordpro.lang': No such file or directory
```
Could fix this by replacing `/debug` by `/release` in the manifest.

2. Metainfo license invalid
```
Running appstreamcli compose
Only accepting components: nl.desbeers.chordprovider, nl.desbeers.chordprovider.desktop
Processing directory: /home/uh/Repositories/Github/Chord-Provider/.flatpak-builder/rofiles/rofiles-0wylBx/files
Composing metadata...
Run failed, some data was ignored.
Errors were raised during this compose run:
nl.desbeers.chordprovider
  E: metainfo-license-invalid
Refer to the generated issue report data for details on the individual problems.
Error: ERROR: appstreamcli compose failed: Child process exited with code 1
```
Can still run it after the error.

3. Missing icons
Icons are still missing for me. Not sure if that's related to the above mentioned error.

<img width="1984" height="1080" alt="Image" src="https://github.com/user-attachments/assets/580b8bb0-43dd-4c56-ac8c-6745ed165184" />

**Comment by CodeShakingSheep** [comment]
Great, with the latest commit issue 1 and 2 are resolved now. However when running `flatpak-builder --run build nl.desbeers.chordprovider.json ChordProvider` I still had the missing icons. I saw the following in the terminal: `Fontconfig error: Cannot load config file "/run/host/font-dirs.xml": No such file: /run/host/font-dirs.xml`. 

It seems to be the same issue as here: https://discourse.flathub.org/t/creating-a-flatpak-fontconfig-error-cannot-load-config-file/6286 as interestingly when I install the app `flatpak-builder --user --install --force-clean build nl.desbeers.chordprovider.json` and then run it with `flatpak run nl.desbeers.chordprovider` the error is gone and I do see all of the icons.

<img width="1916" height="1080" alt="Image" src="https://github.com/user-attachments/assets/6e6afeeb-ebe7-44d3-ac87-2480ec4f3e2f" />

**Comment by Desbeers** [comment]
Sorry for my late reply; busy at my *real* work :-)

Thanks for your support.

I made progress:

![Image](https://github.com/user-attachments/assets/c7f6f7c7-bc43-4cfa-b831-079d9786884e)

Chord diagrams!!!

**Comment by CodeShakingSheep** [comment]
Great progress 😍 Would love to check it out but unfortunately, my flatpak build fails since https://github.com/Desbeers/Chord-Provider/commit/0103f538f4602c941570d4451204cc1cd40506fd . 

```
flatpak-builder build nl.desbeers.chordprovider.json --force-clean

Emptying app dir 'build'
Downloading sources
Starting build of nl.desbeers.chordprovider
Cache miss, checking out last cache hit
========================================================================
Building module ChordProvider in /home/uh/Repositories/Github/Chord-Provider/.flatpak-builder/build/ChordProvider-6
========================================================================
Running: cd ChordProviderGnome && swift build -c release --static-swift-stdlib
Updating https://git.aparoksha.dev/aparoksha/adwaita-swift
error: Couldn’t fetch updates from remote repositories:
    fatal: unable to access 'https://git.aparoksha.dev/aparoksha/adwaita-swift/': Could not resolve host: git.aparoksha.dev
Error: module ChordProvider: Child process exited with code 1
```

It's really strange. The repository is online and I can also successfully ping it from the terminal. Ran the build command several times but always the same.

When I change to the prior commit https://github.com/Desbeers/Chord-Provider/commit/822403eb965054ee2bf4c25790a00f173833b477 the build runs successfully. Any ideas about that @Desbeers ?

**Comment by Desbeers** [comment]
Maybe delete all the hidden files helps? `.build, .swiftpm` etc?

**Comment by CodeShakingSheep** [comment]
That helped. I needed to execute the following steps.

1. Delete hidden folders `.build`, `.swiftpm`, `.flatpak-builder`
2. Resolve swift packages: `cd ChordProviderGnome && swift package resolve`
3. Build (from root dir): `flatpak-builder build nl.desbeers.chordprovider.json --force-clean` or install (from root dir): `flatpak-builder --user --install --force-clean build nl.desbeers.chordprovider.json`

And great progress btw, love the chord diagrams and the file picker!

**Comment by CodeShakingSheep** [comment]
With the latest commit from master I have the following build errors.

```
/run/build/ChordProvider/ChordProviderCore/Sources/ChordProviderCore/Utils/ImageUtils.swift:21:5: warning: 'public' modifier is redundant for static method declared in a public extension
 19 |     /// - Parameter data: The data of the image
 20 |     /// - Returns: The format of the image
 21 |     public static func getImageFormat(data: Data) -> Format {
    |     `- warning: 'public' modifier is redundant for static method declared in a public extension
 22 |         var format: Format = .unknown
 23 |         /// Evaluate the format of the image

/run/build/ChordProvider/ChordProviderCore/Sources/ChordProviderCore/Utils/ImageUtils.swift:42:5: warning: 'public' modifier is redundant for enum declared in a public extension
 40 |     
 41 |     /// Image format
 42 |     public enum Format {
    |     `- warning: 'public' modifier is redundant for enum declared in a public extension
 43 |         /// jpeg image
 44 |         case jpeg

/run/build/ChordProvider/ChordProviderCore/Sources/ChordProviderCore/Utils/ImageUtils.swift:61:5: warning: 'public' modifier is redundant for static method declared in a public extension
 59 |     ///   - arguments: The arguments of the image in the song
 60 |     /// - Returns: The `CGSize` of the image
 61 |     public static func getImageSizeFromArguments(size: CGSize, arguments: ChordProParser.DirectiveArguments?) -> CGSize {
    |     `- warning: 'public' modifier is redundant for static method declared in a public extension
 62 |         var size = size
 63 |         var scale: Double = 1

/run/build/ChordProvider/ChordProviderCore/Sources/ChordProviderCore/Utils/ImageUtils.swift:89:5: warning: 'public' modifier is redundant for static method declared in a public extension
 87 |     /// - Parameter data: The data of the image
 88 |     /// - Returns: The size of the image, if found
 89 |     public static func getImageSize(data: Data) -> CGSize? {
    |     `- warning: 'public' modifier is redundant for static method declared in a public extension
 90 | 
 91 |         let format = getImageFormat(data: data)

/run/build/ChordProvider/ChordProviderCore/Sources/ChordProviderCore/Utils/ImageUtils.swift:26:16: error: cannot find 'CFSwapInt16' in scope
 24 |         var length = UInt16(0)
 25 |         (data as NSData).getBytes(&length, range: NSRange(location: 0, length: 2))
 26 |         switch CFSwapInt16(length) {
    |                `- error: cannot find 'CFSwapInt16' in scope
 27 |         case 0xFFD8:
 28 |             format = .jpeg

/run/build/ChordProvider/ChordProviderCore/Sources/ChordProviderCore/Utils/ImageUtils.swift:100:45: error: cannot find 'CFSwapInt32' in scope
 98 |             (data as NSData).getBytes(&h, range: NSRange(location: 20, length: 4))
 99 | 
100 |             return CGSize(width: Double(Int(CFSwapInt32(w))), height: Double(Int(CFSwapInt32(h))))
    |                                             `- error: cannot find 'CFSwapInt32' in scope
101 | 
102 |         case .gif:

/run/build/ChordProvider/ChordProviderCore/Sources/ChordProviderCore/Utils/ImageUtils.swift:100:82: error: cannot find 'CFSwapInt32' in scope
 98 |             (data as NSData).getBytes(&h, range: NSRange(location: 20, length: 4))
 99 | 
100 |             return CGSize(width: Double(Int(CFSwapInt32(w))), height: Double(Int(CFSwapInt32(h))))
    |                                                                                  `- error: cannot find 'CFSwapInt32' in scope
101 | 
102 |         case .gif:

/run/build/ChordProvider/ChordProviderCore/Sources/ChordProviderCore/Utils/ImageUtils.swift:126:57: error: cannot find 'CFSwapInt16' in scope
124 |                     (data as NSData).getBytes(&w, range: NSMakeRange(i + 7, 2))
125 | 
126 |                     let size = CGSize(width: Double(Int(CFSwapInt16(w))), height: Double(Int(CFSwapInt16(h))) );
    |                                                         `- error: cannot find 'CFSwapInt16' in scope
127 |                     return size
128 |                 } else {

```

**Comment by Desbeers** [comment]
Ah, I used functions from `Core Foundation` for image processing. Found-out that that is not part of `Foundation` and macOS only. Rewrote it so it works on Linux now as well.

**Comment by CodeShakingSheep** [comment]
Build is successful again, thanks 🙏

**Comment by CodeShakingSheep** [comment]
Thanks again for all the work you're putting in this! With the latest commit from today when I open the sample song or any other song I receive

```
ChordProviderCore/resource_bundle_accessor.swift:12: Fatal error: could not load resource bundle: from /app/bin/ChordProviderCore_ChordProviderCore.resources or /run/build/ChordProvider/ChordProviderGnome/.build/x86_64-unknown-linux-gnu/release/ChordProviderCore_ChordProviderCore.resources
```

**Comment by Desbeers** [comment]
It *should* work now again; it was missing resources in the Flatpak...

**Comment by Desbeers** [comment]
I'm about to close this issue.

If anything is missing; let me know!

**Comment by CodeShakingSheep** [comment]
I just updated to the latest version. Love it 😍 Thank you so much for all of your work! I do have 2 wishes:

**Support for strumming patterns in grids**
In a lot of songs I have strumming patterns noted according to https://www.chordpro.org/chordpro/directives-env_grid/#strums

This
```
{comment: Strumming pattern 3: D~UD}
{start_of_grid shape="2x4"}
|s *1 *2 *3 *4 | *1 *2 *3 *4 |
| Am . . . | C . . . |
|s dn .~up d+ . | dn .~up d+ . |
| C . . . | E7 . . . |
|s dn .~up d+ . | dn .~up d+ . |
{end_of_grid}
```

Looks like this in ChordProvider:
<img width="260" height="184" alt="Image" src="https://github.com/user-attachments/assets/8a56807f-5ff4-4039-aa66-cfbbaafb0c25" />

Whereas it looks like this in ChordPro:
<img width="288" height="97" alt="Image" src="https://github.com/user-attachments/assets/5f7f0a10-7cbc-4d88-a429-2406a8df4ab4" />

Could you support strumming patterns in grids?


**Define and display custom directives**
In ChordPro I'm using custom config files where I have custom directives defined. Would it somehow be possible to also define custom directives in ChordProvider and then define where to display them?

This is an example header of a song which displays some custom directives, such as `location`, `year` and 3 links `youtube`, `spotify` and `ultimate`.
<img width="849" height="83" alt="Image" src="https://github.com/user-attachments/assets/4367fc6f-c993-46b1-8e6b-6441017b70df" />

Would something similar be possible in ChordProvider?


**Provide ChordProvider as flatpak**
I've been building ChordProvider using `flatpak-builder` many times and I'd love having an official flatpak version. Would you be interested in me contributing to that by adding a flatpak repo?

**Comment by Desbeers** [comment]
> Support for strumming patterns in grids

I remember the discussion how to add strum pattern to a song. Somewhere is was `{start_of_strum}...{end_of_strum}` so I wrote my own implementation as you can see in the ‘help’ song.

Now it became part of the *Grid* and that makes sense. I will look into that because I like to support *official* directives.

That brings me to the next subject:

> Define and display custom directives

That’s a though one....

- **ChordPro** is a *standard* format. For a good reason. It is not bound to an *implementation*. In my opinion, every *chordpro song* can be opened in in any *implementation* and should look reasonable.
- I’m a `Swift` coder; a strongly typed language. Every *official* **ChordPro** `directive` is defined in the `Enum`.
- I have no idea how to display your *custom* directive

The goal of **Chord Provider** for Linux is in real *Gnome* style. It is what is. I like that. There is no configuration like in the official ChordPro implementation. There never will be.

While I like the official **ChordPro** implementation very much; it’s a beast that can be configured to the last detail.

So, no...

However, you can use tags for you links? Didn’t try with an image. I suggested that to the official standard and it is added.

<img width="326" height="142" alt="Image" src="https://github.com/user-attachments/assets/4c206fb8-076b-4f61-acef-1459fbdca2f0" />

`location` seems like a nice directive to add. `version` might be a more universal name?
`year` is already implemented; I will add it to my render (same for `album`)

> Provide ChordProvider as flatpak

Thank for your offer; but its not ready yet. Once it goes out in the wild its reputation is set. I found too many bugs and have no clue how I did my stuff in `C`; just good luck. I want to know my own code before I make a release.

**Comment by CodeShakingSheep** [comment]
Thank you for your explanations. I understand that it's not feasible atm to support custom directives. That's fine. Also thanks for looking into the strumming patterns in grids, appreciate it!

Sure, I can use tags for links. Can you tell me how to do that?
```
{tag <a href="https://youtu.be/OQuQV6u8-tk">YouTube</a>}
{tag https://youtu.be/OQuQV6u8-tk}
```

This turns into this in ChordProvider and the links are not clickable.

<img width="468" height="47" alt="Image" src="https://github.com/user-attachments/assets/bf859600-be60-418a-b5bd-8dbc3d143dfc" />

Regarding directives to add:

- `location`: I use this to save the location where I've played this song for the first time. So, I'm not sure about `version` but also a possibility.
- `language`: I also use a tag for the song language according to https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes , so for example an English song has `{language: EN}` or a song with English and French has `{language: EN / FR}`. Could you implement and render this?
- `genre`: Pretty self-explanatory.
- `difficulty`: I know this is very subjective but it helps me to know which songs I can play fluently and which ones not.
- `source`: Also an individual tag which I use to save where I've listened to a song for the first time. Could be `concert XYZ` or `Spotify playlist`.

Let me know what you think about my proposed directives. And also feel free to ping me once you feel you're ready for a flatpak release :)

**Comment by Desbeers** [comment]
> Thank you for your explanations. I understand that it's not feasible atm to support custom directives. That's fine. Also thanks for looking into the strumming patterns in grids, appreciate it.

## Custom directives
Custom directives will not be supported. Never. they goes agains the nature of an *open standard* in my opinion.
## Tag
This should work; I’ll check.

## Strumming

About *strumming*; I made progress:

<img width="912" height="712" alt="Image" src="https://github.com/user-attachments/assets/c7617d52-a553-4cc7-b445-89810dee1cd7" />

**Comment by Desbeers** [comment]
A full link in a `{tag}` works for me:

<img width="1092" height="650" alt="Image" src="https://github.com/user-attachments/assets/38d2c1c6-4ecd-4737-b165-06df5065f97a" />

A simple url string does not and that makes sense. It's long an ugly :-)

In the file browser on the welcome screen; full links are clickable now.

Unfortunately, you can't use an image in the tag. Pango does not support that.

Please have a look at the strum patterns; it should work reasonably well now!

**Comment by Desbeers** [comment]
Found out that links should not contain an `&`. Pango does not like that...

**Comment by CodeShakingSheep** [comment]
Just tested the new version. Strumming patterns in grids looking good, thanks for that! 3 small issues:

**Support transpose directive**
In some `chordpro` files I use `{transpose: +1}` for example. I would really appreciate if ChordProvider would render those files with the transposed chords from the beginning (instead of manually having to adopt it in ChordProvider's Transpose settings dialog each time when opening it).

**Support pango in grids (for highlighting chords)**
In many songs I have highlighted chords that are being transitioned into mid strumming pattern in red. 
```
{start_of_grid shape="4x4"}
|s *1 *2 *3 *4 | *1 *2 *3 *4 | *1 *2 *3 *4 | *1 *2 *3 *4 |
| B . . . | B . . . | B . . . | B . . . |
|s dn .~up d+ . | dn .~up d+ . | dn .~up d+ . | dn .~up d+ . |
| E . . . | D#m . . . | D#m . <span color="red">G#m</span> . | G#m . . . |
|s dn .~up d+ . | dn .~up d+ . | dn .~up d+ . | dn .~up d+ . |
{end_of_grid}
```
Would look like this in ChordPro.

<img width="363" height="94" alt="Image" src="https://github.com/user-attachments/assets/0ea7ae31-2402-4cbf-b370-34c9f102c5e9" />

Can this be achieved in ChordProvider?

**Little cosmetic issues**
I noticed that the upper part of lines is sometimes being cut off a tiny bit in some songs. For example the line of the artist's name or Bridge headings.

<img width="185" height="102" alt="Image" src="https://github.com/user-attachments/assets/f6eae5cb-a4b9-4068-b897-bc898394eb4e" />

See the `R` is cut off a little.

<img width="88" height="63" alt="Image" src="https://github.com/user-attachments/assets/fc05cc79-aa93-4cdb-835f-3d3236a18be1" />

See the `B` is cut off a little.

Edit: Forgot to mention: Links work fine now with `<a>`. Bummer though that Pango doesn't support an image in a tag. Looks much nicer in my opinion. Anyways thanks for making regular links clickable.

**Comment by Desbeers** [comment]
> Support transpose directive

Makes sense; will add that. However, transposing further with the dialog will *not* alter the source. I just don't like that.

> Support pango in grids (for highlighting chords)

Work in progress... If I want to support pango, I want to support it for text parts and chords in verse, chorus etc as well.

<img width="1146" height="712" alt="Image" src="https://github.com/user-attachments/assets/c9a82e6f-a96d-4fcb-9c96-29fc4ad34e97" />

> Little cosmetic issues

It has something to do with the `zoom` level of the text; investigating...

**Comment by CodeShakingSheep** [comment]
Just wanted to give some feedback on the latest changes:

> Support transpose directive

This works great. Thank you, makes it so much smoother to open a song and play it right away without having to fiddle around.


> Support pango in grids (for highlighting chords)

Also works great.

> Little cosmetic issues

The cut off upper part of lines is still present for me.

**Scrolling direction**
I'm not sure if I just haven't noticed it before or if this was introduced by a change recently. Opening a long song a horizontal scroll bar appears, so I can scroll more to the right to see the last parts of the songs. I would prefer vertical scrolling as I can just use the mouse scrolling wheel which is easier and quicker imo. Perhaps this could be a setting in preferences if the user prefers horizontal or vertical scrolling? And even with horizontal scrolling I would prefer if using the mouse wheel would scroll further.

**Comment by Desbeers** [comment]
> Scrolling direction

There is already a button in the toolbar that let you switch between list-view (vertical scrolling) and page-view (horizontal scrolling).

I cannot make vertical-scrolling with just the mouse-wheel. Shift+scroll does work; it’s just how GTK works.

> The cut off upper part of lines is still present for me

I hard-coded the Adwaita Sans font in the CSS; maybe that was the problem. So I removed that. Can you give it a try?

**Comment by Desbeers** [comment]
I've added `snippets` to the editor to add directives. Super cool! Still *work in process*. That was not easy!

**Comment by CodeShakingSheep** [comment]
**Scrolling direction**
Oh, just saw it. That works perfectly!

**Little cosmetic issues**
The cut off upper letters are still present for me in the subtitle (artist name and year below title). Though, thery are not present anymore on the Verse headings.

**Snippets**
How do I use these? I checked the preferences but didn't find anything related to snippets. In the Log output of a song I still see `This is an unknown directive` entries. Where would I define my custom directives?

Thanks so much for all the energy you're putting into this project!

**Comment by Desbeers** [comment]
Ah, `snippets` is a `GtkSourceView` thing to add *completions* for a text; its not for custom directives.

See `chordpro.snippets` in the `GtkSourceView` package.

So if you type `{start_` it will show a popup with all directives starting with that. Same for all other **known** directives. Just for quicker typing.

> Little cosmetic issues

I don’t see this. You might want to play a bit with the fonts in `Markup+css.swift` in the source to see if you can find the issue:

```
.song-subtitle {
    font-size: \(1.2 * baseFontSize)px;
    font-weight: normal;
}
```

Or in `GtkRender+PageHeader.swift` where the header is displayed:

```
VStack {
    Text(song.metadata.title)
        .style(.title)
    Text(subtitle)
        .style(.subtitle)
        .padding(5, .top)
        /// Metadata
        (etc)
```

> Thanks so much for all the energy you're putting into this project!

Thanks, its a fun project!

**Comment by CodeShakingSheep** [comment]
Hi again,
Thanks for your continuous work on this project. I haven't dived into the cut off lines. It's on my list. Just wanted to report a bug regarding HTML markup.

<img width="933" height="162" alt="Image" src="https://github.com/user-attachments/assets/e6e6f4db-2a26-4181-b4d8-b3bf3891c7f3" />

Whenever there is a `transpose` directive in a song the HTML markup isn't rendered correctly anymore. I've encountered this in different songs that have a `transpose` directive. It doesn't seem to happen in songs without a `transpose` directive (at least I haven't found one in my list so far). If you need more info about this please reach out.

**Comment by Desbeers** [comment]
Can you give me a sample song where this is happening? I can't reproduce it...

**Comment by CodeShakingSheep** [comment]
> Can you give me a sample song where this is happening? I can't reproduce it...

```
{title Test Song}
{transpose: 1}

{start_of_grid shape="4x4"}
|s *1 *2 *3 *4 | *1 *2 *3 *4 | *1 *2 *3 *4 | *1 *2 *3 *4 |
| Gm . . . | Eb . . . | Eb . . . | Cm . . . |
|s dn .~up d+ d | dn .~up d+ d | dn .~up d+ d | dn .~up d+ d |
| Cm . <span color="red">F</span> . | Gm . . . | Cm . <span color="red">F</span> . | Gm . . . |
|s dn .~up d+ d | dn .~up d+ d | dn .~up d+ d | dn .~up d+ d |
{end_of_grid}
```

Looks like this

<img width="814" height="315" alt="Image" src="https://github.com/user-attachments/assets/3621422e-129f-4a20-a5c8-c59fed9b2115" />

**Comment by Desbeers** [comment]
Ah, Pango markup was not enabled for chord-toggles. That is fixed now.

There are some more Pango issues, like nested tags... Working on that!

**Comment by CodeShakingSheep** [comment]
> Ah, Pango markup was not enabled for chord-toggles. That is fixed now.
> 
> There are some more Pango issues, like nested tags... Working on that!

Is fixed for me after pulling latest commits, thanks!

**Comment by CodeShakingSheep** [comment]
Hi,
I updated Chord-Provider after a longer time. Just wanted to report that `flatpak-builder build nl.desbeers.chordprovider.json --force-clean` exits with this

```
Building for production...
/usr/lib/gcc/x86_64-unknown-linux-gnu/15.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/sdk/swift6/lib/swift_static/linux/libFoundationEssentials.a(Data+Writing.swift.o): note: the message above does not take linker garbage collection into account
/usr/lib/gcc/x86_64-unknown-linux-gnu/15.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /usr/lib/sdk/swift6/lib/swift_static/linux/libFoundationEssentials.a(Data+Writing.swift.o): in function `$s20FoundationEssentials19createTemporaryFile33_FC9EC52B075D2ACCFF86F1C9F84293BELL2at6inPath6prefix7options7variants5Int32V_SStSS_AA0Q5OrURLOSSAA4DataV14WritingOptionsVSSSgtKFAJ_SStSgSpys4Int8VGSgKXEfU_':
_ThreadLocal.swift.o:(.text+0xac9): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'
error: link command failed with exit code 1 (use -v to see invocation)
/usr/lib/gcc/x86_64-unknown-linux-gnu/15.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lfluidsynth: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[35/36] Linking ChordProvider
```

This didn't happen before.

**Comment by Desbeers** [comment]
I've added `fluidsynth` to play chords and metronome. It build fine for me as flatpak on Fedora 43 for Intel and ARM.

Delete any cache files?

**Comment by Desbeers** [comment]
Any update? I consider my port done for its first version.

**Comment by CodeShakingSheep** [comment]
> Any update? I consider my port done for its first version.

I deleted cache and ran `swift package resolve` from `ChordProviderGnome` but still the same error.

**Comment by Desbeers** [comment]
I'm unable to reproduce this error... Maybe you need to install the dev-package for `fluidsynth`?

I've build flatpaks for arm and intel, maybe they work for you? Can you please test?

https://github.com/Desbeers/Chord-Provider/releases/tag/Flatpak

**Comment by CodeShakingSheep** [comment]
I don't know why it wasn't building with fluidsynth. Anyways, I used the flatpak pre-release and it works fine. Cool feature that you're able to play the chords :)

Edit: Just played around a bit with the new version. It's really cool! One thing I noticed is that chords in brackets are not recognized properly, see screenshot. They are supported in official ChordPro though. Can you add support for those?

<img width="352" height="183" alt="Image" src="https://github.com/user-attachments/assets/6c5364fc-07b6-4c11-95fb-b19991d72d66" />

Edit 2: And a little UX cosmetic issue: Could you turn the play icon into a stop icon while the pattern is being played?

**Comment by Desbeers** [comment]
Nice to know my flatpak actually works; thanks for testing!

> One thing I noticed is that chords in brackets are not recognized properly

Fixed. Did not know ChordPro supported that. Just curious, what is the meaning of it? Play soft or so?

> Could you turn the play icon into a stop icon while the pattern is being played?

It is not a button but a toggle so I did not bother. But tried it and it looks better, so done.

**Comment by CodeShakingSheep** [comment]
> Fixed. Did not know ChordPro supported that. Just curious, what is the meaning of it? Play soft or so?

I use round brackets to indicate that it's an optional chord (or a quick passing chord) that may be played.

Downloaded and installed the release from yesterday but seems that the 2 changes aren't included yet.

From my perspective, the app is in a great state now and ready to be launched to flathub. Any plans when you will officially package it?

**Comment by Desbeers** [comment]
The releases are build manually, I've updated them just now.

I'm still working on the Chords Database, lots of *edge-cases*...

For flathub, I'm not in a hurry. Please debug it as good as you can, I have no other testers than you :-)

Its a fun project, I actually moved to Fedora as my main OS and dropped the macOS version...

**Comment by CodeShakingSheep** [comment]
Cool, just downloaded the new one. 2 issues I reported work fine now 🥳 

> Please debug it as good as you can, I have no other testers than you :-)

Sure, I'm happy to test some more :) Here are some findings.

1. Chords are not rendered correctly after a text in round brackets

Check out how the text from "Caught in the undertow[...]" is rendered. There are 2 issues here from my side. Firstly, the round brackets have been removed from the text. I think they should be kept. Secondly, subsequent chords are not being rendered as chords but as text, see screenshot.

<img width="980" height="334" alt="Image" src="https://github.com/user-attachments/assets/57b0e74c-a029-49a5-975a-a32a58c4da37" />

Here is the text you can use for debugging. 
```
{start_of_verse}
[Em]  I'm tired of being what you [C]want me to be
[G]Feeling so faithless lost [D]under the surface
[Em]  Don't know what you're ex[C]pecting of me
Put [G]under the pressure of [D]walking in your sh[C]oes[D]
{end_of_verse}

(Caught in the undertow, just caught in the undertow)
Every [Em]step I take is an[G]other mistake to [C]you[D]

(Caught in the undertow, just caught in the undertow)
```

2. Rendering of a song's year

This is also a little cosmetic issue. Was wondering why year is hidden behind the "More..." button. There's enough room to display it next to capo. My suggestion would be us a small calendar icon and then render the year next to it. What do you think?

<img width="189" height="127" alt="Image" src="https://github.com/user-attachments/assets/e9344f88-a19e-4a41-8b10-b830552dc305" />

**Comment by Desbeers** [comment]
> Chords are not rendered correctly after a text in round brackets

That was because that section was not wrapped between `{start_of_verse}/{end_of_verse}` and since the first line didn't contain any chords my parser decided that is was a *Textblock*. The editor shows a warning for that...

Anyway, I made the parser smarter, so now, if there is any chord in the paragraph it will be a *Verse*.

The *round brackets* removal was because of how a *Textblock* was rendered. That is now fixed.

> Rendering of a song's year

The header was hard coded to only show `key, capo, time and bpm` (when available) and dropped everything else in "More.."

Now its a bit smarter and shows maximum the first 4 items and the others, if still something left, in "More...".

(No new Flatpaks yet, I found some more issues to fix first...)

**Comment by CodeShakingSheep** [comment]
Your changes sound good. Will wait for the new flatpak to test again. In the meantime I found another issue with a bit of a complex strumming pattern. Take a look at this:

```
{comment: Strumming pattern 13: DDD DUDUD}
{start_of_grid shape="1x4"}
|s *1~*& *2~*& *3~*& *4~*& |
| . . . . |
|s dn~dn d+~.~dn~up dn~up~dn~. d+~.~dn~up |
|s *5~*& *6~*& *7~*& *8~*& |
| . . . . |
|s dn~up~dn~. d+~.~dn~up .~up~.~up dn~up~dn~up |
{end_of_grid}
```

In ChordPro it looks as expected:

<img width="287" height="137" alt="Image" src="https://github.com/user-attachments/assets/a4a43903-af69-458a-9502-3800e5c0cd9c" />

Whereas in Chord Provider it looks like this:

<img width="339" height="235" alt="Image" src="https://github.com/user-attachments/assets/726fd244-32b9-49b7-8792-6a7989d8dfc4" />

Note how the positions of the & signs are off. This is the Wonderwall strumming pattern if that helps 😉 Also this strumming pattern doesn't play in Chord Provider (no sound when clicking play sign, just transformed play sign into stop sign).

**Comment by Desbeers** [comment]
(cross post)

I added something really *cool*! The MIDI player is **strum** aware in the grid!

Made new `Flatpak`s

If you go to Settings -> Appearance and enable "Debug" you will see a lot of songs available for debugging in the 'start' View.

Still work in progress...

**Comment by CodeShakingSheep** [comment]
> I added something really _cool_! The MIDI player is **strum** aware in the grid!

Awesome, love it! 😍 I read it's still WIP. Anyways, just wanted to add it would be cool if strums without *explicit* chords would still be played. I'll give you an example.

```
{start_of_grid shape="2x4"}
|s *1 *2 *3 *4 | *1 *2 *3 *4 |
| Am . . . | G . . . |
|s dn .~up d+ d | dn .~up d+ d |
| Dm . . . | F . . . |
|s dn .~up d+ d | dn .~up d+ d |
{end_of_grid}
```
This plays only the first downstrum for each chord.

```
{start_of_grid shape="2x4"}
|s *1 *2 *3 *4 | *1 *2 *3 *4 |
| Am Am Am Am | G G G G |
|s dn .~up d+ d | dn .~up d+ d |
| Dm Dm Dm Dm | F F F F |
|s dn .~up d+ d | dn .~up d+ d |
{end_of_grid}
```
This plays all strums fine but I don't want to note my strumming patterns like that as it adds noise. Would be great if first strumming pattern would be played like this is being played.

**Comment by Desbeers** [comment]
> Your changes sound good. Will wait for the new flatpak to test again. In the meantime I found another issue with a bit of a complex strumming pattern. Take a look at this:

Interesting challenge! I have to rewrite code I have not touched for many moons :-D Working on it, that is my joy of programming. I don't use AI for that; I let my brain boil ;-)

>  Anyways, just wanted to add it would be cool if strums without explicit chords would still be played.

Reading the **ChordPro** specs, a '.' means *no chord here*. While I agree that is looks *noisy* it is correct behaviour  in my opinion.

One more thing I were would like your opinion:

As coded now, a chord in a *Grid* looks **above** for its strum. While looking at the *specs*, it seems to me that the **stroke** is *below* the chord. I don't like that. Your opinion?

**Comment by Desbeers** [comment]
Progression! I think my parser renders *Wonderwall* now ok, see below:

<img width="2914" height="1938" alt="Image" src="https://github.com/user-attachments/assets/77539b1d-539b-4f8c-b311-d94f5a290520" />

It also fixes your *strums without explicit chords* request; see how I dealt with that in the screenshot.

No commit yet, code is a bit *messy*, but please have a look at the screenshot what is still to be discussed...

**Comment by Desbeers** [comment]
And while coding this, I found another challenge... *Wonderwall* has capo 2, correct?  So, if you define a capo in the song; the chords should be like it is but the MIDI player should transpose it... Doable :-)

**Comment by CodeShakingSheep** [comment]
Such nice progress! 🙌 

> One more thing I were would like your opinion:
> As coded now, a chord in a Grid looks above for its strum. While looking at the specs, it seems to me that the stroke is below the chord. I don't like that. Your opinion?

I'm a bit confused what you mean here. In both ChordPro and Chord Provider the strums are below the chords. I'm ok with that (if that's what you are referring to).

Regarding your questions in the screenshot:

> Is the grid correct?
First grid from Wonderwall looks correct to me now. Cool!

> Should I make all parts the same width?
Good question. My first impulse was to say yes for consistency. But I agree it can stretch the grid too much (esp. with long chord names such as `A7sus4`). Another approach could be to find a way to find a more compact notation but I don't have any good idea for that right now. E.g. add a line break between `A7` and `sus4`. Although this would take up more space vertically then. Not sure I'd like that.

> Do you like the automatic added chords that are dimmed?
The concept is fine with me. I like that the source is being kept clean that way and that the strumming pattern is still being played correctly. On the other hand, in reference to your previous question this can also stretch a grid a lot...

Looking at the example strum grid on https://www.chordpro.org/chordpro/directives-env_grid/#strums it seems to be a common assumption that the last chord on the line is being played because otherwise the strums _in between_ notes would be unnecessary. So, would be justified to play the last chord on the line while not displaying it, don't you think? 

And another thing. Did you consider muted strums, such as `dx`, `ux` or `x`? I think the sound should be explicitly muted for those.

> And while coding this, I found another challenge... _Wonderwall_ has capo 2, correct? So, if you define a capo in the song; the chords should be like it is but the MIDI player should transpose it... Doable :-)

Oh, I hadn't been thinking about that. Yes, Wonderwall has capo 2 and it would be dope if it played the chords based on capo 2 (still the same ones `Em7`, `G`, `Dsus4`, `Asus7` etc., not transposing them in the sense of the `transpose` directive).

Thanks for your work again! Happy to engage in further brainstorming.

**Comment by Desbeers** [comment]
Capo support is added, that was an easy cream on the pie :-D Rewriting the grid was different.... Rewrote my code many times. But I like that; the fun of my hobby!

> And another thing. Did you consider muted strums, such as dx, ux or x? 

They are now muted; as far as my limited MIDI player can do...

> Thanks for your work again! 

It is not work :-D

The foundation is in place. I made new Flatpak's.

Next challenge is to play *Tabs*...

**Comment by CodeShakingSheep** [comment]
> Capo support is added, that was an easy cream on the pie :-D Rewriting the grid was different.... Rewrote my code many times. But I like that; the fun of my hobby!

Great you're enjoying it!

> It is not work :-D

Well, then let's say for your energy 😉 
> 
> Next challenge is to play _Tabs_...

Oh yes, I was about to suggest that :)

Some other small things came to mind.

1. Highlight currently played chord in strumming patterns
For example UG highlights the currently played chord and strum in the strumming pattern red and I really like this feature to easily follow along. Can you implement something like that?

2. Sync metronome and strumming pattern
I wanted to hear the strumming pattern and the metronome at the same time but they are not autmatically in sync. If the strumming pattern is already playing and I start the metronome, can it wait a little bit and then start on the first beat? And vice versa, if the metronome is already playing and I start the strumming pattern, can the strumming pattern sync in with the metronome on first beat?

3. Define tuning in chord preferences
I believe the currently played chords are based on 440 Hz. Would be nice to have the option to use another tuning such as 432 Hz. Not sure if fluidsynth supports that.

**Comment by Desbeers** [comment]
> Highlight currently played chord in strumming patterns

Good idea; done! (no sound in capture is it was playing!)

https://github.com/user-attachments/assets/e3db67ad-c462-4db2-a1d9-8f56716ea2f8

> Sync metronome and strumming pattern

Also done!

> Define tuning in chord preferences

Tuning is based on the current instrument, so you have to make a new instrument for that... See `Chords Databse` in the menu...


Again messy code, so need to cleanup, but its' working!

**Comment by CodeShakingSheep** [comment]
>  Screencast.From.2026-04-17.14-22-14.mp4 
That looks nice :)

> Tuning is based on the current instrument, so you have to make a new instrument for that... See Chords Databse in the menu...

It seems to be a bit of an overkill for me having to add a new instrument just for a different tuning frequency. Because all the chord definitions would stay the same, just the Hz would change...

Another issue regarding strumming patterns I just came across. Take a loot at this:

```
{start_of_grid shape="2x4"}
|s *1 *2 *3 *4 | *1 *2 *3 *4 |
| C . <span color="red">(D)</span> . | Em . <span color="red">(D)</span> . |
|s dn dn~up .~up dn~up | dn dn~up .~up dn~up |
| G . . . | Am . . . |
|s dn dn~up .~up dn~up | dn dn~up .~up dn~up |
{end_of_grid}
```

It's rendered like this:

<img width="379" height="165" alt="Image" src="https://github.com/user-attachments/assets/c7fbb7bd-a6d8-44b7-a51f-d17a233f6a3e" />

There are 2 issues imo:

1. The (D) should still be shown in brackets in the dimmed chords.
2. This pattern is not being played correctly. There is an additional (faulty) down strum being played on the 3rd beat (where the initial (D) is written). Imo a strum should be played based on a noted strum (not a noted chord).
3. There shouldn't be a dot `.` between the 3 first `G`s and the 3 last `G`s. Same for the `Am`s.

Looking forward to a new release :)

**Comment by Desbeers** [comment]
> It seems to be a bit of an overkill for me having to add a new instrument just for a different tuning frequency. Because all the chord definitions would stay the same, just the Hz would change...

A different tuning *is* another instrument and its easy to clone a build-in instrument... Let me think about that...

> The (D) should still be shown in brackets in the dimmed chords.

Yes, it should.

> This pattern is not being played correctly. There is an additional (faulty) down strum being played on the 3rd beat (where the initial (D) is written). Imo a strum should be played based on a noted strum (not a noted chord).

Hmm, yes, but there *is* a chord defined...

> There shouldn't be a dot . between the 3 first Gs and the 3 last Gs. Same for the Ams.

That is by design, it means "don't play a note here" but I reconsider it...

----

Anyway, I fixed those issues but the result was smelly spaghetti-code and I don't like that... So, rewriting the grid parser again :-)))) WIP!

**Comment by Desbeers** [comment]
Progression! No new Flathub because I don't have an Intel around me at the moment...

<img width="3456" height="2170" alt="Image" src="https://github.com/user-attachments/assets/820adcc5-af51-4204-acf9-bcac4ca75f48" />

- I let the dots as they are, they have a meaning, *don't play here*. It is according ChordPro standard; except the reference implementation shows nothing there. My render does *not* make all columns equal because that will make it too big. So I have to show something...
- The player plays all your grids well now.
- When starting the metronome, the volume of the chord-playing will be lower, so you can here the metronome better. I like such details. 

While I coded the grid-player just for fun as a challenge; I found-out it is actually very useful! I'm a better programmer than guitar player and I'm adding grids to my songs to play along...

---

Do you have some more interesting grids for me that are fine in ChordPro?

**Comment by CodeShakingSheep** [comment]
Yes, I absolutely agree that the grid-player is super useful! Let me share a realization I had while looking for more interesting grids for you.

On UG I had a song with this strumming pattern:
<img width="124" height="108" alt="Image" src="https://github.com/user-attachments/assets/3ed67a97-09ea-4245-a008-5777e878106f" />

In Chordpro I noted the pattern like this:

```
{start_of_grid shape="2x4"}
|s *1 *2 *3 *4 | *1 *2 *3 *4 |
| Am . . . | Em . . . |
|s dn dn~up dn~up . | dn dn~up dn~up . |
| G . . . | D . . . |
|s dn dn~up dn~up . | dn dn~up dn~up . |
{end_of_grid}
```

Then by playing the strumming pattern in your grid-player I noticed that it was off because there was this pause on the 4th beat. But, the original song doesn't have a full beat pause. Syncing the song with the metronome didn't match either because the metronome played 4 beats. That was when I understood that the song was not in 4/4 but in 3/4. So, I added `{time 3/4}` and I corrected the strumming pattern to

```
{start_of_grid shape="2x3"}
|s *1 *2 *3 | *1 *2 *3 |
| Am . . | Em . . |
|s dn dn~up dn~up | dn dn~up dn~up |
| G . . | D . . |
|s dn dn~up dn~up | dn dn~up dn~up |
{end_of_grid}
```

Now both metronome as well as the strumming pattern match fine with the song. I don't think I would have noticed this error in my notation without your grid-player. I'm in the process of goind though my song collection and adding more directives, such as `tempo` and `time` because now I can actually make use of them with the grid-player. Was also stoked that Chord-Provider automatically adopted the metronome to the time change from `4/4` to `3/4`. Super cool! It's more and more becoming my number 1 software for `chordpro` files. Though I'm still using ChordPro for generating PDF song books based on song genres which I then copy to my ebook reader.

So, for now I don't have any more interesting strumming patterns after digging through my collection. If I find one later I will share it with you. I have some other small findings though:

**1. Newline characters `\n`**
In chordpro I can have newline characters `\n`. For example I use one in a verse label `{start_of_verse: Verse 1 \n(Earth)}` to keep the label column as small as possible. In chordpro it is rendered like this

<img width="73" height="189" alt="Image" src="https://github.com/user-attachments/assets/5749a864-e631-4b1d-8833-bdfed0f07484" />

In Chord-Provider it's rendered like this:

<img width="143" height="50" alt="Image" src="https://github.com/user-attachments/assets/707cbeab-27d6-471e-a1b2-952f277dfb69" />

I'd suggest to either just filter out `\n` and not display it or to add an actual line break. Although, in Chord-Provider as the labels are rendered above the parts I'd prefer it `\n` is just stripped away and not displayed.

**2. Colored dimmed chords**
This is just a little cosmetic issue. Would love if the dimmed chords respected the original chord's color. So, how about keeping the color for colored dimmed chords but to dim it down? For example, the dimmed G would be in dimmed red here. What do you think?

<img width="141" height="57" alt="Image" src="https://github.com/user-attachments/assets/b9d9211e-40d1-41ac-bdca-9fa644864dd9" />

**Comment by CodeShakingSheep** [comment]
> A different tuning _is_ another instrument and its easy to clone a build-in instrument... Let me think about that...

I took some time to look into the frequency topic. So, I managed to export the current guitar tuning form the Chords Database. Then I have a JSON file which has chord definitions and a tuning object at the end

```
  "tuning" : [
    "E2",
    "A2",
    "D3",
    "G3",
    "B3",
    "E4"
  ]
```

Tuning would stay the same, no matter if the frequency is 432 Hz or 440 Hz. So, I don't see any way in Chord-Provider to change the frequency currently. I will explain what I mean by sharing some screenshots from the Tuner app I'm using (https://codeberg.org/thetwom/Tuner). In Tuner I have a setting like this which allows me to just change the frequency (note that both the instrument (guitar) as well as the tunings `E2`, `A2`, `D3`, `G3`, `B3`, `E4` stay exactly the same).

<img width="300" alt="Image" src="https://f-droid.org/repo/de.moekadu.tuner/en-US/phoneScreenshots/04.png" />

This is the app's instrument setting view (which is separate from changing a defined instrument's frequency). Imo it only makes sense to add a new instrument there which has custom tuning.

<img width="300" alt="Image" src="https://f-droid.org/repo/de.moekadu.tuner/en-US/phoneScreenshots/02.png" />

As expressed I don't know if fluidsynth support a different Hz frequency than the default 440 Hz. Might be something to be researched... Hope this makes it more clear.

**Comment by Desbeers** [comment]
*a picture speaks a thousand words*:

<img width="3456" height="2170" alt="Image" src="https://github.com/user-attachments/assets/6e796a71-cde1-44a1-b223-202d6a327ccf" />

(look also at the font of the chords)

**Comment by Desbeers** [comment]
> Hope this makes it more clear.

This is for later, my brain is already boiling :-D

**Comment by CodeShakingSheep** [comment]
> _a picture speaks a thousand words_:
> 
> <img alt="Image" width="2000" height="1256" src="https://private-user-images.githubusercontent.com/58348935/582959638-6e796a71-cde1-44a1-b223-202d6a327ccf.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzcwNjg2ODgsIm5iZiI6MTc3NzA2ODM4OCwicGF0aCI6Ii81ODM0ODkzNS81ODI5NTk2MzgtNmU3OTZhNzEtY2RlMS00NGExLWIyMjMtMjAyZDZhMzI3Y2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDI0VDIyMDYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZTFhMmQ5YmZmYWYzYjhmNjBlODY4MDgwMmFlYzk0NzUwNDk3NjYxMTAwZDQ1MzJmOWNmNmIyMjE0NDgwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.2eK3TBXFl75UOtJ4E1Vrlp-VPbF9ppE4aKQCPYYfmfw">
> (look also at the font of the chords)

Cool, colored dimmed chords and also colored accented chords look great 🙌 

Noticed something else. Negative transpose directive values such as `{transpose -2}` don't work correctly. That transposes 2 semitones up (instead of down). This works in ChordPro.

**Comment by Desbeers** [comment]
> Negative transpose directive values such as {transpose -2} don't work correctly. That transposes 2 semitones up (instead of down). This works in ChordPro.

Good finding, thanks! Fixed...

**Comment by Desbeers** [comment]
> As expressed I don't know if fluidsynth support a different Hz frequency than the default 440 Hz. Might be something to be researched... Hope this makes it more clear.

Two times *yes* :-) fluidsynth supports different Hz frequencies and it is also more clear...

Experimenting with it but I don't hear any difference... But, I'm a little bit old (haha) and also listen on laptop speakers. If I detune a **lot** I can hear the difference, so it looks like it is working...

Anyway, it is just a matter of implementing this in the UI. What to you expect? Set either '440' or '432', or some more fixed values or give it any value? Do those frequencies also have names? Like '415' is baroque tuning? I like presets more, because else it looks to technical for my simple UI ;-)

**Comment by CodeShakingSheep** [comment]
> Experimenting with it but I don't hear any difference... But, I'm a little bit old (haha) and also listen on laptop speakers. If I detune a lot I can hear the difference, so it looks like it is working...

Yes, it can be hard to hear but if you hear the difference after detuning a lot it sounds like it's working :)

> Anyway, it is just a matter of implementing this in the UI. What to you expect? Set either '440' or '432', or some more fixed values or give it any value? Do those frequencies also have names? Like '415' is baroque tuning? I like presets more, because else it looks to technical for my simple UI ;-)

Good questions. Personally, I'm only looking to select 432 Hz. In the Tuner app you can set any Hz frequency in a text field. If you want to have it more preset like perhaps use the mentioned frequencies here https://shop.gamutmusic.com/pages/understanding-tunings ? I'm not sure if this is a selection representing the most popular frequencies though...

**Comment by Desbeers** [comment]
For now, I just implement a global setting in *Preferences* with a stepper. It works *on the fly*, so when starting a grid and going to *Preferences* to detune I can clearly hear the difference.

Just some code cleanup and its good to go. I'll make a new Flatpak soon for you to play with it...

So, **STAY TUNED**!!!! :-D

**Comment by Desbeers** [comment]
Done! There are new Flatpak's :-)

**Comment by CodeShakingSheep** [comment]
Just played around with the new flatpak a bit. The automatic strumming pattern / metronome sync is so helpful! Transposing negative values works fine. Also changed the frequency in the midi settings and it works fine for me (I hear the difference). Also liked that you removed the warnings for directives with colons e.g. `{artist: xyz}` because all of my songs use colons.

I have one very curious finding (which has been present in the past flatpak version as well but I wanted to wait if your new release would fix this). For some of my songs the strumming patterns appear strange in Chord-Provider while they appear totally fine in ChordPro. The patterns themselves are valid and it's even patterns which I have in other songs too (just with different chords) which render fine in Chord-Provider. So, I did some troubleshooting to find out why and it seems that Chord-Provider only supports a specific type of line endings `lf`.

For example in a song I have this. A pretty simple grid.

```
{start_of_grid shape="2x4"}
|s *1 *2 *3 *4 | *1 *2 *3 *4 |
| D# . . . | F . . . |
|s dn .~up d+ . | dn .~up d+ . |
| Gm . . . | F . . . |
|s dn .~up d+ . | dn .~up d+ . |
{end_of_grid}
```

In ChordPro it looks like this:

<img width="288" height="84" alt="Image" src="https://github.com/user-attachments/assets/0fb993ef-8384-465c-a97f-02db320e5b40" />

In Chord-Provider it renders like this:

<img width="395" height="255" alt="Image" src="https://github.com/user-attachments/assets/bb3da1c5-194e-4ba6-a618-68062f91c589" />

Somehow it's split up and when I play one of the parts it only plays one down strum per chord.

I tried to fix it by copying the exact same pattern from another song and then changed the chords manually and voila everything looked fine again in chordpro. My song collection is checked in to a git repository and after fixing it there was a git diff.

<img width="425" height="327" alt="Image" src="https://github.com/user-attachments/assets/fbbab546-ab7b-4920-bc93-bea6ac7ef4d2" />

Just with no human visible changes. So, it had to be something about formatting. I ran `git ls-files --eol` in my repository's song folder. While most of the song files had `lf` line endings others had `crlf` line endings. The 2 files that I manually fixed had `mixed` line endings now. While all `lf` files were fine in Chord-Provider all `crlf` songs had this broken strumming pattern rendering like in the screenshot above. So, the fix is to set line endings to `lf` for all my song files which is easily doable in VSCode. 

Was wondering how come that some of my files have `lf` and some `crlf`. Probably because I've used different editors over the years (ChordPro, VSCode, Chord-Provider). Perhaps at some point I had line endings set to `crlf` in VSCode. I've never paid attention to that before for my song collection. But now that it makes a difference I will set all my song files to `lf` (also for more consistency). That fixes the issue for me.

Wow, this got longer than I expected :D So, in summary Chord-Provider messes up strumming patterns for files with `crlf` line endings. I guess the question now is if you want to fix this from your side because there might be other people with song files with `crlf` line endings. What's your take on this?

> So, **STAY TUNED**!!!! :-D

Definitely staying TUNED especially for playable tabs 🤩

**Comment by Desbeers** [comment]
> What's your take on this?

Ah, known issue that I fixed in the macOS version loooong time ago. Forgot to add it to the Linux version, so its fixed now...

**Comment by Desbeers** [comment]
I *might* have fixed your issue with building Chord Provider from source because of Fluidsynth... The Flatpak manifest was deleting headers during the build that Swift needed and on my computer, it found the headers somewhere else...

Can you give it a try?

**Comment by Desbeers** [comment]
> Definitely staying TUNED especially for playable tabs 🤩

It's there! But WIP, found a lot of issues and I'm sure you will find more :-D

**Comment by Desbeers** [comment]
I close this issue, because the Linux port is done. Far better than its macOS version ;-)

Thanks for the challenge!
